language: php
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
    allow_failures:
        - php: 5.5
        - php: 5.4

before_script:
  - composer self-update
  - composer update
script: php ./vendor/bin/phpunit test
